enhance selective module performance with gradle-profiler benchmark

diff --git a/gradle/profiler/bin/gradle-profiler b/gradle/profiler/bin/gradle-profiler
--- a/gradle/profiler/bin/gradle-profiler
+++ b/gradle/profiler/bin/gradle-profiler
@@ -15,6 +15,8 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 #
+# SPDX-License-Identifier: Apache-2.0
+#
 
 ##############################################################################
 #
@@ -55,7 +57,7 @@
 #       Darwin, MinGW, and NonStop.
 #
 #   (3) This script is generated from the Groovy template
-#       https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
+#       https://github.com/gradle/gradle/blob/HEAD/platforms/jvm/plugins-application/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
 #       within the Gradle project.
 #
 #       You can find Gradle at https://github.com/gradle/gradle/.
@@ -80,13 +82,12 @@ do
     esac
 done
 
-APP_HOME=$( cd "${APP_HOME:-./}.." && pwd -P ) || exit
-
-APP_NAME="gradle-profiler"
+# This is normally unused
+# shellcheck disable=SC2034
 APP_BASE_NAME=${0##*/}
-
-# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_PROFILER_OPTS to pass JVM options to this script.
-DEFAULT_JVM_OPTS=""
+# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
+APP_HOME=$( cd -P "${APP_HOME:-./}.." > /dev/null && printf '%s
+' "$PWD" ) || exit
 
 # Use the maximum available, or set MAX_FD != -1 to use that value.
 MAX_FD=maximum
@@ -114,7 +115,7 @@ case "$( uname )" in                #(
   NONSTOP* )        nonstop=true ;;
 esac
 
-CLASSPATH=$APP_HOME/lib/gradle-profiler-0.19.0.jar:$APP_HOME/lib/gradle-tooling-api-7.2.jar:$APP_HOME/lib/annotations-3.0.1.jar:$APP_HOME/lib/guava-27.1-android.jar:$APP_HOME/lib/jopt-simple-5.0.4.jar:$APP_HOME/lib/config-1.3.3.jar:$APP_HOME/lib/commons-math3-3.6.1.jar:$APP_HOME/lib/javaparser-core-3.18.0.jar:$APP_HOME/lib/ant-compress-1.5.jar:$APP_HOME/lib/commons-io-2.6.jar:$APP_HOME/lib/flightrecorder-8.0.1.jar:$APP_HOME/lib/dd-plist-1.23.jar:$APP_HOME/lib/gson-2.8.6.jar:$APP_HOME/lib/client-protocol-0.19.0.jar:$APP_HOME/lib/slf4j-simple-1.7.10.jar:$APP_HOME/lib/slf4j-api-1.7.30.jar:$APP_HOME/lib/jcip-annotations-1.0.jar:$APP_HOME/lib/jsr305-3.0.2.jar:$APP_HOME/lib/failureaccess-1.0.1.jar:$APP_HOME/lib/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:$APP_HOME/lib/checker-compat-qual-2.5.2.jar:$APP_HOME/lib/error_prone_annotations-2.2.0.jar:$APP_HOME/lib/j2objc-annotations-1.1.jar:$APP_HOME/lib/animal-sniffer-annotations-1.17.jar:$APP_HOME/lib/ant-1.10.12.jar:$APP_HOME/lib/commons-compress-1.14.jar:$APP_HOME/lib/xz-1.6.jar:$APP_HOME/lib/dec-0.1.2.jar:$APP_HOME/lib/common-8.0.1.jar:$APP_HOME/lib/ant-launcher-1.10.12.jar:$APP_HOME/lib/encoder-1.2.2.jar:$APP_HOME/lib/lz4-java-1.7.1.jar
+CLASSPATH=$APP_HOME/lib/gradle-profiler-0.22.0.jar:$APP_HOME/lib/gradle-tooling-api-7.2.jar:$APP_HOME/lib/annotations-3.0.1.jar:$APP_HOME/lib/guava-32.1.2-jre.jar:$APP_HOME/lib/config-1.3.3.jar:$APP_HOME/lib/commons-math3-3.6.1.jar:$APP_HOME/lib/javaparser-core-3.18.0.jar:$APP_HOME/lib/jopt-simple-5.0.4.jar:$APP_HOME/lib/ant-compress-1.5.jar:$APP_HOME/lib/commons-compress-1.27.1.jar:$APP_HOME/lib/commons-io-2.16.1.jar:$APP_HOME/lib/flightrecorder-8.0.1.jar:$APP_HOME/lib/dd-plist-1.23.jar:$APP_HOME/lib/gson-2.11.0.jar:$APP_HOME/lib/client-protocol-0.22.0.jar:$APP_HOME/lib/slf4j-simple-1.7.10.jar:$APP_HOME/lib/slf4j-api-1.7.30.jar:$APP_HOME/lib/jcip-annotations-1.0.jar:$APP_HOME/lib/jsr305-3.0.2.jar:$APP_HOME/lib/failureaccess-1.0.1.jar:$APP_HOME/lib/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:$APP_HOME/lib/checker-qual-3.33.0.jar:$APP_HOME/lib/error_prone_annotations-2.27.0.jar:$APP_HOME/lib/ant-1.10.15.jar:$APP_HOME/lib/xz-1.6.jar:$APP_HOME/lib/dec-0.1.2.jar:$APP_HOME/lib/commons-codec-1.17.1.jar:$APP_HOME/lib/commons-lang3-3.16.0.jar:$APP_HOME/lib/common-8.0.1.jar:$APP_HOME/lib/ant-launcher-1.10.15.jar:$APP_HOME/lib/encoder-1.2.2.jar:$APP_HOME/lib/lz4-java-1.7.1.jar
 
 
 # Determine the Java command to use to start the JVM.
@@ -133,22 +134,29 @@ location of your Java installation."
     fi
 else
     JAVACMD=java
-    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
+    if ! command -v java >/dev/null 2>&1
+    then
+        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
 
 Please set the JAVA_HOME variable in your environment to match the
 location of your Java installation."
+    fi
 fi
 
 # Increase the maximum file descriptors if we can.
 if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
     case $MAX_FD in #(
       max*)
+        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
+        # shellcheck disable=SC2039,SC3045
         MAX_FD=$( ulimit -H -n ) ||
             warn "Could not query maximum file descriptor limit"
     esac
     case $MAX_FD in  #(
       '' | soft) :;; #(
       *)
+        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
+        # shellcheck disable=SC2039,SC3045
         ulimit -n "$MAX_FD" ||
             warn "Could not set maximum file descriptor limit to $MAX_FD"
     esac
@@ -193,11 +201,15 @@ if "$cygwin" || "$msys" ; then
     done
 fi
 
-# Collect all arguments for the java command;
-#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_PROFILER_OPTS can contain fragments of
-#     shell script including quotes and variable substitutions, so put them in
-#     double quotes to make sure that they get re-expanded; and
-#   * put everything else in single quotes, so that it's not re-expanded.
+
+# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_PROFILER_OPTS to pass JVM options to this script.
+DEFAULT_JVM_OPTS=""
+
+# Collect all arguments for the java command:
+#   * DEFAULT_JVM_OPTS, JAVA_OPTS, JAVA_OPTS, and optsEnvironmentVar are not allowed to contain shell fragments,
+#     and any embedded shellness will be escaped.
+#   * For example: A user cannot expect ${Hostname} to be expanded, as it is an environment variable and will be
+#     treated as '${Hostname}' itself on the command line.
 
 set -- \
         -classpath "$CLASSPATH" \
