master: update gradle profiler

diff --git a/gradle/profiler/bin/gradle-profiler b/gradle/profiler/bin/gradle-profiler
--- a/gradle/profiler/bin/gradle-profiler
+++ b/gradle/profiler/bin/gradle-profiler
@@ -1,18 +1,14 @@
 #!/bin/sh
 
 #
-
 # Copyright © 2015-2021 the original authors.
 #
-
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
-
 #      https://www.apache.org/licenses/LICENSE-2.0
 #
-
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
@@ -22,93 +18,46 @@
 
 ##############################################################################
 #
-
 #   gradle-profiler start up script for POSIX generated by Gradle.
 #
-
 #   Important for running:
 #
-
-#   (1)
-You need
-a POSIX
--
-compliant shell
-to run
-this script.
-If your
-/bin/
-sh is
+#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
 #       noncompliant, but you have some other compliant shell such as ksh or
 #       bash, then to run this script, type that shell name before the whole
 #       command line, like:
 #
-
 #           ksh gradle-profiler
 #
-
 #       Busybox and similar reduced shells will NOT work, because this script
 #       requires all of these POSIX shell features:
-#         *
-functions;
-#         * expansions «$var», «${
-var}», «${
-var:-default}», «${
-var+SET}»,
-#           «${
-var#prefix}», «${
-var%suffix}», and «
-$( cmd )
-»;
-#         *
-compound commands
-having a
-testable exit
-status, especially «case»;
-#         *
-various built
--
-in commands
-including «command», «set», and «ulimit».
+#         * functions;
+#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
+#           «${var#prefix}», «${var%suffix}», and «$( cmd )»;
+#         * compound commands having a testable exit status, especially «case»;
+#         * various built-in commands including «command», «set», and «ulimit».
 #
-
 #   Important for patching:
 #
-
-#   (2)
-This script
-targets any
-POSIX shell, so
-it avoids
-extensions provided
+#   (2) This script targets any POSIX shell, so it avoids extensions provided
 #       by Bash, Ksh, etc; in particular arrays are avoided.
 #
-
 #       The "traditional" practice of packing multiple parameters into a
 #       space-separated string is a well documented source of bugs and security
 #       problems, so this is (mostly) avoided, by progressively accumulating
 #       options in "$@", and eventually passing that to Java.
 #
-
 #       Where the inherited environment variables (DEFAULT_JVM_OPTS, JAVA_OPTS,
 #       and GRADLE_PROFILER_OPTS) rely on word-splitting, this is performed explicitly;
 #       see the in-line comments for details.
 #
-
 #       There are tweaks for specific operating systems such as AIX, CygWin,
 #       Darwin, MinGW, and NonStop.
 #
-
-#   (3)
-This script
-is generated
-from the
-Groovy
-template
+#   (3) This script is generated from the Groovy template
 #       https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
 #       within the Gradle project.
 #
-
 #       You can find Gradle at https://github.com/gradle/gradle/.
 #
 ##############################################################################
@@ -116,28 +65,19 @@ template
 # Attempt to set APP_HOME
 
 # Resolve links: $0 may be a link
-app_path = $0
+app_path=$0
 
 # Need this for daisy-chained symlinks.
 while
-APP_HOME = ${app_path % "${app_path##*/}"}
-#
-leaves a
-trailing /; empty if
-no leading
-path
-[ -h "$app_path" ]
+    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
+    [ -h "$app_path" ]
 do
-ls = $(ls - ld
-"$app_path" )
-link = ${ls#
-*' -> '}
-case
-$link in
-#(
-/*)   app_path=$link ;; #(
-*)    app_path=$APP_HOME$link ;;
-esac
+    ls=$( ls -ld "$app_path" )
+    link=${ls#*' -> '}
+    case $link in             #(
+      /*)   app_path=$link ;; #(
+      *)    app_path=$APP_HOME$link ;;
+    esac
 done
 
 APP_HOME=$( cd "${APP_HOME:-./}.." && pwd -P ) || exit
@@ -146,156 +86,95 @@ APP_NAME="gradle-profiler"
 APP_BASE_NAME=${0##*/}
 
 # Add default JVM options here. You can also use JAVA_OPTS and GRADLE_PROFILER_OPTS to pass JVM options to this script.
-DEFAULT_JVM_OPTS = ""
+DEFAULT_JVM_OPTS=""
 
 # Use the maximum available, or set MAX_FD != -1 to use that value.
-MAX_FD = maximum
+MAX_FD=maximum
 
-warn() {
-    echo
-    "$*"
-}
+warn () {
+    echo "$*"
+} >&2
 
->&2
-
-die() {
+die () {
     echo
+    echo "$*"
     echo
-    "$*"
-    echo
-    exit
-    1
-}
-
->&2
+    exit 1
+} >&2
 
 # OS specific support (must be 'true' or 'false').
-cygwin = false
-msys = false
-darwin = false
-nonstop = false
+cygwin=false
+msys=false
+darwin=false
+nonstop=false
 case "$( uname )" in                #(
-CYGWIN* )
-cygwin = true;; #(
-Darwin* )
-darwin = true;; #(
-MSYS* | MINGW* )
-msys = true;; #(
-NONSTOP* )
-nonstop = true;;
+  CYGWIN* )         cygwin=true  ;; #(
+  Darwin* )         darwin=true  ;; #(
+  MSYS* | MINGW* )  msys=true    ;; #(
+  NONSTOP* )        nonstop=true ;;
 esac
 
-        CLASSPATH = $APP_HOME / lib / gradle - profiler - 0.18.0.jar
-:$APP_HOME/lib/gradle-tooling-api-7.2.jar:$APP_HOME/lib/annotations-3.0.1.jar:$APP_HOME/lib/guava-27.1-android.jar:$APP_HOME/lib/jopt-simple-5.0.4.jar:$APP_HOME/lib/config-1.3.3.jar:$APP_HOME/lib/commons-math3-3.6.1.jar:$APP_HOME/lib/javaparser-core-3.18.0.jar:$APP_HOME/lib/ant-compress-1.5.jar:$APP_HOME/lib/commons-io-2.6.jar:$APP_HOME/lib/flightrecorder-8.0.1.jar:$APP_HOME/lib/dd-plist-1.23.jar:$APP_HOME/lib/gson-2.8.6.jar:$APP_HOME/lib/client-protocol-0.18.0.jar:$APP_HOME/lib/slf4j-simple-1.7.10.jar:$APP_HOME/lib/slf4j-api-1.7.30.jar:$APP_HOME/lib/jcip-annotations-1.0.jar:$APP_HOME/lib/jsr305-3.0.2.jar:$APP_HOME/lib/failureaccess-1.0.1.jar:$APP_HOME/lib/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:$APP_HOME/lib/checker-compat-qual-2.5.2.jar:$APP_HOME/lib/error_prone_annotations-2.2.0.jar:$APP_HOME/lib/j2objc-annotations-1.1.jar:$APP_HOME/lib/animal-sniffer-annotations-1.17.jar:$APP_HOME/lib/ant-1.10.12.jar:$APP_HOME/lib/commons-compress-1.14.jar:$APP_HOME/lib/xz-1.6.jar:$APP_HOME/lib/dec-0.1.2.jar:$APP_HOME/lib/common-8.0.1.jar:$APP_HOME/lib/ant-launcher-1.10.12.jar:$APP_HOME/lib/encoder-1.2.2.jar:$APP_HOME/lib/lz4-java-1.7.1.jar
+CLASSPATH=$APP_HOME/lib/gradle-profiler-0.19.0.jar:$APP_HOME/lib/gradle-tooling-api-7.2.jar:$APP_HOME/lib/annotations-3.0.1.jar:$APP_HOME/lib/guava-27.1-android.jar:$APP_HOME/lib/jopt-simple-5.0.4.jar:$APP_HOME/lib/config-1.3.3.jar:$APP_HOME/lib/commons-math3-3.6.1.jar:$APP_HOME/lib/javaparser-core-3.18.0.jar:$APP_HOME/lib/ant-compress-1.5.jar:$APP_HOME/lib/commons-io-2.6.jar:$APP_HOME/lib/flightrecorder-8.0.1.jar:$APP_HOME/lib/dd-plist-1.23.jar:$APP_HOME/lib/gson-2.8.6.jar:$APP_HOME/lib/client-protocol-0.19.0.jar:$APP_HOME/lib/slf4j-simple-1.7.10.jar:$APP_HOME/lib/slf4j-api-1.7.30.jar:$APP_HOME/lib/jcip-annotations-1.0.jar:$APP_HOME/lib/jsr305-3.0.2.jar:$APP_HOME/lib/failureaccess-1.0.1.jar:$APP_HOME/lib/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:$APP_HOME/lib/checker-compat-qual-2.5.2.jar:$APP_HOME/lib/error_prone_annotations-2.2.0.jar:$APP_HOME/lib/j2objc-annotations-1.1.jar:$APP_HOME/lib/animal-sniffer-annotations-1.17.jar:$APP_HOME/lib/ant-1.10.12.jar:$APP_HOME/lib/commons-compress-1.14.jar:$APP_HOME/lib/xz-1.6.jar:$APP_HOME/lib/dec-0.1.2.jar:$APP_HOME/lib/common-8.0.1.jar:$APP_HOME/lib/ant-launcher-1.10.12.jar:$APP_HOME/lib/encoder-1.2.2.jar:$APP_HOME/lib/lz4-java-1.7.1.jar
 
 
 # Determine the Java command to use to start the JVM.
-if [ -n "$JAVA_HOME" ]; then
-if [ -x "$JAVA_HOME/jre/sh/java" ];
-then
-# IBM's JDK on AIX uses strange locations for the executables
-        JAVACMD = $JAVA_HOME / jre / sh / java
-else
-JAVACMD = $JAVA_HOME / bin / java
-fi
-if [ ! -x "$JAVACMD" ];
-then
-        die
-"ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME
+if [ -n "$JAVA_HOME" ] ; then
+    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
+        # IBM's JDK on AIX uses strange locations for the executables
+        JAVACMD=$JAVA_HOME/jre/sh/java
+    else
+        JAVACMD=$JAVA_HOME/bin/java
+    fi
+    if [ ! -x "$JAVACMD" ] ; then
+        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME
 
-Please set
-the JAVA_HOME
-variable in
-your environment
-to match
-the
-        location
-of your
-Java installation
-."
-fi
+Please set the JAVA_HOME variable in your environment to match the
+location of your Java installation."
+    fi
 else
-JAVACMD = java
-which java
->/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
+    JAVACMD=java
+    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
 
-Please set
-the JAVA_HOME
-variable in
-your environment
-to match
-the
-        location
-of your
-Java installation
-."
+Please set the JAVA_HOME variable in your environment to match the
+location of your Java installation."
 fi
 
 # Increase the maximum file descriptors if we can.
-if ! "$cygwin" && ! "$darwin" && ! "$nonstop"; then
-case
-$MAX_FD in
-#(
-max*)
-MAX_FD = $(ulimit - H - n) ||
-         warn
-"Could not query maximum file descriptor limit"
-esac
-case
-$MAX_FD in
-#(
-'' | soft) :;; #(
-*)
-ulimit -n "$MAX_FD" ||
-warn "Could not set maximum file descriptor limit to $MAX_FD"
-esac
-        fi
+if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
+    case $MAX_FD in #(
+      max*)
+        MAX_FD=$( ulimit -H -n ) ||
+            warn "Could not query maximum file descriptor limit"
+    esac
+    case $MAX_FD in  #(
+      '' | soft) :;; #(
+      *)
+        ulimit -n "$MAX_FD" ||
+            warn "Could not set maximum file descriptor limit to $MAX_FD"
+    esac
+fi
 
 # Collect all arguments for the java command, stacking in reverse order:
-#   *
-args from
-the command
-line
-#   *
-the main
-
-class name
-
+#   * args from the command line
+#   * the main class name
 #   * -classpath
-#   * -
-D...appname
-settings
-#   * --module-
-path (only
-if needed)
-#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and
-GRADLE_PROFILER_OPTS environment
-variables.
+#   * -D...appname settings
+#   * --module-path (only if needed)
+#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_PROFILER_OPTS environment variables.
 
 # For Cygwin or MSYS, switch paths to Windows format before running java
-if "$cygwin" || "$msys";
-then
-        APP_HOME = $(cygpath--
-path --mixed "$APP_HOME" )
-CLASSPATH = $(cygpath--
-path --mixed "$CLASSPATH" )
+if "$cygwin" || "$msys" ; then
+    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
+    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )
 
-JAVACMD = $(cygpath--
-unix "$JAVACMD" )
+    JAVACMD=$( cygpath --unix "$JAVACMD" )
 
-# Now convert the arguments - kludge to limit ourselves to /bin/sh
-for arg do
-if
-case
-$arg in
-#(
--*)   false;;                            # don't mess with options #(
-/?*)
-t = ${arg#
-/}
-t =
-/${
-t%%/*}              # looks like a POSIX filepath
+    # Now convert the arguments - kludge to limit ourselves to /bin/sh
+    for arg do
+        if
+            case $arg in                                #(
+              -*)   false ;;                            # don't mess with options #(
+              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                     [ -e "$t" ] ;;                      #(
               *)    false ;;
             esac
@@ -324,6 +203,12 @@ set -- \
         -classpath "$CLASSPATH" \
         org.gradle.profiler.Main \
         "$@"
+
+# Stop when "xargs" is not available.
+if ! command -v xargs >/dev/null 2>&1
+then
+    die "xargs is not available"
+fi
 
 # Use "xargs" to parse quoted args.
 #
